### ISSUE TITLE
Error in cursor transformation inserting or deleting '\n'

### ISSUE THREAD

**Issue by crcastle** [marcelklehr/gulf-codemirror#1]
Hi @marcelklehr! I'm building a little project that's a collaborative code editor and webrtc video conference.  You can check out a demo here: https://cursor-transform-issue.herokuapp.com.  It builds upon a lot of the awesome stuff you've wrote: gulf and this repo, gulf-codemirror.

The issue I'm seeing has to do with maintaining user A's cursor position when user B adds or deletes lines above user A's cursor.  I'm wondering if you have noticed this and in which repo is should be addressed: gulf-codemirror, gulf, or ottypes/text repo?

Here are repro steps:
1. Open https://cursor-transform-issue.herokuapp.com/testing in two browser tabs.  Can be the same browser.  You should see a full-screen CodeMirror code editor with the following text in it.  Ignore the webrtc boxes on the right.  

```
abc
de
f
```

If you don't see this content then someone else has messed with it.  Just change the URL path `/testing` to whatever you want and a fresh document will be started with the above text.
2. In the first tab, place the cursor at the end of the document. (after the `f` character)
3. In the second tab, where the cursor should by default be at the very beginning of the document, hit enter -- i.e. insert `\n`
4. Now go back to the first tab and you'll notice that the cursor is no longer after the `f` character!
5. The cursor in the first tab will continue to move around if you add or delete lines above it in the other tab.

The issue seems to be related to how cursor position is transformed.  When any other character (not `\n`) is inserted in front of the other tab's cursor, the index should just be incremented -- i.e. if the cursor is at position 3 and a new character is added in front of it, the new position should be 4.  This is what ottypes/text does.  However, this doesn't seem correct for the `\n` character.

Here are the relevant bits of code where the non-editing user's cursor position is calculated:
1. https://github.com/marcelklehr/gulf-codemirror/blob/master/index.js#L44-L47
2. http://codemirror.net/doc/manual.html#posFromIndex
3. https://github.com/ottypes/text/blob/master/lib/text.js#L408
4. https://github.com/ottypes/text/blob/master/lib/text.js#L374-L377

cc @josephg since I'm beginning to think this should be addressed in the ottypes/text repo.

I'm curious if you agree this is a bug and if so, where it should be fixed?

Let me know if this doesn't make sense.  I tried to be clear in my explanation, but my brain has been deep in this for a while and I might have skipped over some assumptions.

Interestingly, I found that this issue also affects the hivejs project.  Try the repro steps at https://beta.hivejs.org/documents/1.  Open it up in two tabs, put the cursor at the end of the editor in one tab and hit enter at the beginning of the other tab.

Edits: I hit 'create issue' button before I finished writing up the issue.

**Comment by marcelklehr** [comment]
Hey chris,

I haven't tested gulf-codemirror extensively, so: sorry that you had to run into this problem. Still, this is a very good find. The problem lies in gulf-codemirror: The cursor's current index is [calculated after applying the changes](https://github.com/marcelklehr/gulf-codemirror/blob/master/index.js#L45), but it must happen _before_ applying them.

After fixing this, another bug becomes apparent (at least in hive), which I filed on codemirror's issues: https://github.com/codemirror/CodeMirror/issues/3905

**Comment by crcastle** [comment]
ohhhhhh, i see now.  glad that it was such a quick fix.  thanks!
